### ISSUE TITLE
Part 11 Exercises 11.9 cy.visit() failed trying to load http://127.0.0.1:5000/ when running e2e test on GitHub Actions

### ISSUE THREAD

**Issue by yingtu35** [fullstack-hy2020/fullstack-hy2020.github.io#2998]
I tried to follow the instruction in exercise 11.9 and added the e2e tests to my GitHub Actions workflow. Although the cypress test passed locally, it didn't pass on GitHub Actions and keeps displaying this error: 
![image](https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/assets/91551415/7c5c7089-e66e-4366-abe3-55867b12f459)

I am pretty sure I didn't mistype anything because I basically copy and paste the code in the exercise.

I've googled the issue and found some pages with similar issues like this one [https://github.com/cypress-io/github-action/issues/634](url). I've tried the approaches suggested on the page but none of them worked. Up to the moment, I am not sure where the issue comes from.

If someone has faced the same or similar issue, pls share if you have fixed it and how you deal with it. Thanks!

**Comment by nGonium** [comment]
I think either 
1) The server is not starting before the tests are run or,
2) The server has not completed starting up before the tests are run or,
3) The server is running on a different port than expected. 

If the issue only affects the pipeline and not your local version, that would suggest something wrong with the pipeline. Ensure you have this section in your yaml, in this specific order:
```yaml
- name: build 
  run: npm run build
- name: test 
  run: npm run test
- name: e2e tests
  uses: cypress-io/github-action@v5
  with:
    command: npm run test:e2e
    start: npm run start-prod
    wait-on: http://localhost:5000
```
(Double check the indentation, mine might be wrong if I overlooked something).

If that doesn't work, verify your local process is the *exact* same as it would be in the pipeline. If you have a .env file in the root directory, delete it. Delete `node_modules` and `dist`. Reinstall the modules with `npm install`, then `npm run build` then `npm run start-prod` and finally, in a second terminal, `npm run test:e2e`. If this runs fine but the pipeline still fails, I'm not sure where to go from there.
