### ISSUE TITLE
Part 11 material is missing explanation on Status Checks

### ISSUE THREAD

**Issue by ElvannAbendroth** [fullstack-hy2020/fullstack-hy2020.github.io#3966]
When I set up the branch protection, nothing shows up in the status checks.  I've looked into Github documentation but the information is not answering my question, or isn't really helpful in understanding and solving the issue.  I'm not sure what I did different in how I set up my workflow.

Here's what it looks like on my end:

![Image](https://github.com/user-attachments/assets/52b76bbd-a8f4-46d7-8e43-35e11a8a054c)

Proposed documentation from Github:
- https://docs.github.com/en/rest/commits/statuses?apiVersion=2022-11-28
- https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/about-status-checks

Here's my workflow file:

```
# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-20.04
    if: ${{ !contains(github.event.head_commit.message, '#no-test') }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Lint Style
        run: npm run eslint
      - name: Tests
        run: npm test
      - name: Build
        run: npm run build
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: [tests]
    concurrency: deploy-group # optional: ensure only one action runs at a time
    if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#nodeploy') }}
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy to Fly
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  tag_release:
    needs: [deploy]
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

```

An explanation would be appreciated, however I would also suggest adding this explanation in the course material so others who are coming accross the same issues might have a better idea on how to setup their own workflow to get the status checks to appear. The current course material simply assumes that checks should appear there without really explaining really what they are besides the fact that they appear there.
