### ISSUE TITLE
<em> elements missing in Linux

### ISSUE THREAD

**Issue by goodman65** [fullstack-hy2020/fullstack-hy2020.github.io#954]
I have Linux to read the course `https://fullstackopen.com/`. And I found `<em> ` elements missing.

The problem is here:

```CSS
.course em {
    font-family: Courier;
    font-style: normal;
    background-color: hsla(0,0%,88.2%,.6);
    padding: 1px 5px 2px;
}
```
(edited)
It turned out simply adding `monospace` didn't help. It only helped when I deleted `Courier` and changed the font to others like `Menlo`.

my guess: when using chrome in Ubuntu Linux, if only `Courier New` is installed instead of `Courier`, chrome will not treat `Courier` properly.
So maybe it's a better idea to change the font in the section of CSS to something else.

[Courier Font](https://github.com/maseyyi/font-courier/blob/master/Courier.ttf) in case anyone needs it.
